version: '3.8'

services:
  mysql:
    container_name: mysql_picpay_desafio
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: picpay_desafio
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always 
    networks:
      - backend

  flyway:
    image: boxfuse/flyway:latest-alpine
    command: -url=jdbc:mysql://mysql:3306/picpay_desafio -user=admin -password=admin migrate
    networks:
      - backend
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    restart: on-failure
    depends_on:
      - mysql

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - backend
    restart: always

  picpay-desafio:
    container_name: picpay-desafio
    image: picpay-desafio
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/picpay_desafio
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - kafka
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
